---
# Note: Gray Area Licenses (requires additional work and review): EPL-1.0, CDDL-1.0, CDDL-1.1

manifest_file: papers_manifest.yml
accept:
  - Apache-2.0 # Use of Apache conditioned upon no contribution of modified code back to original author/open source community.
  - MIT
  - ISC
  - BSD-2-Clause-FreeBSD
  - BSD-2-Clause-NetBSD
  - BSD-2-Clause
  - BSD-3-Clause-Attribution
  - BSD-3-Clause-Clear
  - BSD-3-Clause-LBNL
  - BSD-3-Clause
  - BSD-4-Clause-UC
  - BSD-4-Clause
  - BSD-Protection
  - MS-PL
  - Ruby # Use of Ruby conditioned upon selection of the BSDL option for any internal/non-source-available modifications.
  - ISC
  - CC0-1.0

reject:
  - AGPL-1.0
  - AGPL-3.0
  - GPL-2.0-with-GCC-exception # Certain GPL licenses have a Classpath exception that we have accepted in limited circumstances because it enable us to put it under our closed, proprietary license.
  - GPL-2.0-with-autoconf-exception
  - GPL-2.0-with-bison-exception
  - GPL-2.0-with-classpath-exception
  - GPL-2.0-with-font-exception
  - GPL-2.0
  - GPL-3.0-with-GCC-exception
  - GPL-3.0-with-autoconf-exception
  - GPL-3.0
  - LGPL-2.0
  - LGPL-2.1
  - LGPL-3.0
  - Artistic-1.0-Perl
  - Artistic-1.0-cl8
  - Artistic-1.0
  - Artistic-2.0

exceptions:
  - "github.com/newrelic/nri-kubernetes/src/apiserver"
  - "github.com/newrelic/nri-kubernetes/src/storage"
  - "github.com/newrelic/nri-kubernetes/src/config"
  - "github.com/newrelic/nri-kubernetes/src/data"
  - "github.com/newrelic/nri-kubernetes/src/definition"
  - "github.com/newrelic/nri-kubernetes/src/client"
  - "github.com/newrelic/nri-kubernetes/src/ksm"
  - "github.com/newrelic/nri-kubernetes/src/ksm/client"
  - "github.com/newrelic/nri-kubernetes/src/ksm/metric"
  - "github.com/newrelic/nri-kubernetes/src/kubelet"
  - "github.com/newrelic/nri-kubernetes/src/kubelet/client"
  - "github.com/newrelic/nri-kubernetes/src/kubelet/metric"
  - "github.com/newrelic/nri-kubernetes/src/metric"
  - "github.com/newrelic/nri-kubernetes/src/prometheus"
  - "github.com/newrelic/nri-kubernetes/e2e/jsonschema/schema"
  - "github.com/newrelic/nri-kubernetes/vendor/github.com/newrelic/infra-integrations-sdk/args"
  - "github.com/newrelic/nri-kubernetes/vendor/github.com/newrelic/infra-integrations-sdk/cache"
  - "github.com/newrelic/nri-kubernetes/vendor/github.com/newrelic/infra-integrations-sdk/log"
  - "github.com/newrelic/nri-kubernetes/vendor/github.com/newrelic/infra-integrations-sdk/metric"
  - "github.com/newrelic/nri-kubernetes/vendor/github.com/newrelic/infra-integrations-sdk/sdk"
  - "github.com/newrelic/nri-kubernetes/vendor/github.com/juju/ratelimit" # LGPL-3.0 but includes a Classpath giving permission (https://www.gnu.org/software/classpath/license.html)
  - "github.com/newrelic/nri-kubernetes/e2e/gcp" #e2e tests
  - "github.com/newrelic/nri-kubernetes/e2e/helm" #e2e tests
  - "github.com/newrelic/nri-kubernetes/e2e/jsonschema" #e2e tests
  - "github.com/newrelic/nri-kubernetes/e2e/k8s" #e2e tests
  - "github.com/newrelic/nri-kubernetes/e2e/timer" #e2e tests
  - "github.com/newrelic/nri-kubernetes/e2e/retry" #e2e tests

