{{- if .Values.karpenterNodePool.enabled -}}
---
# ClusterRole to allow KSM to list and watch NodePools
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-nodepool-reader
  labels:
    app: {{ .Release.Name }}
rules:
  - apiGroups: ["karpenter.sh"]
    resources: ["nodepools"]
    verbs: ["list", "watch"]
---
# ClusterRoleBinding to bind the role to KSM service account
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-nodepool-reader
  labels:
    app: {{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-nodepool-reader
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-kube-state-metrics
    namespace: {{ .Release.Namespace }}
{{- end }}