{{- if .Values.persistentVolumeClaim.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-pv-claim
  labels:
    environment: staging
    team: storage-team
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: {{ .Release.Name }}-pv-class
  resources:
    requests:
      storage: 3Mi
{{- end }}
