apiVersion: v1
version: 1.0.0
appVersion: "3.7"
description: This chart creates two pending alpine pods. One non scheduled because the resource limits are too small. The other scheduled. Only for test purposes.
name: alpine-pending