{{- if and (.Values.controlPlane.enabled) (.Values.rbac.create) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "newrelic.labels" . | nindent 4 }}
  name: {{ include "common.naming.fullname" . }}-controlplane
rules:
  - apiGroups: [""]
    resources:
      - "nodes/metrics"
      - "nodes/stats"
      - "nodes/proxy"
    verbs: ["get", "list"]
  - apiGroups: [ "" ]
    resources:
      - "pods"
      - "nodes"
    verbs: [ "get", "list", "watch" ]
  - nonResourceURLs: ["/metrics"]
    verbs: ["get", "head"]
  {{- if .Values.rbac.pspEnabled }}
  - apiGroups:
      - extensions
    resources:
      - podsecuritypolicies
    resourceNames:
      - privileged-{{ include "common.naming.fullname" . }}
    verbs:
      - use
  {{- end -}}
{{- $namespaces := include "newrelic.roleBindingNamespaces" . | fromYaml -}}
{{- if $namespaces.roleBindingNamespaces}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "newrelic.labels" . | nindent 4 }}
  name: {{ include "common.naming.fullname" . }}-secrets
rules:
  - apiGroups: [""]
    resources:
      - "secrets"
    verbs: ["get", "list", "watch"]
{{- end -}}
{{- end -}}
