apiVersion: v2
name: newrelic-infrastructure
description: A Helm chart to deploy the New Relic Kubernetes monitoring solution
home: https://docs.newrelic.com/docs/kubernetes-pixie/kubernetes-integration/get-started/introduction-kubernetes-integration/
icon: https://newrelic.com/themes/custom/curio/assets/mediakit/NR_logo_Horizontal.svg
sources:
  - https://github.com/newrelic/nri-kubernetes/
  - https://github.com/newrelic/nri-kubernetes/tree/main/charts/newrelic-infrastructure
  - https://github.com/newrelic/infrastructure-agent/
version: 3.55.3
appVersion: 3.50.2
dependencies:
  - name: common-library
    version: 1.3.3
    repository: "https://helm-charts.newrelic.com"
maintainers:
  - name: danielstokes
    url: https://github.com/danielstokes
  - name: dbudziwojskiNR
    url: https://github.com/dbudziwojskiNR
  - name: kondracek-nr
    url: https://github.com/kondracek-nr
  - name: Philip-R-Beckwith
    url: https://github.com/Philip-R-Beckwith
  - name: TmNguyen12
    url: https://github.com/TmNguyen12
keywords:
  - infrastructure
  - newrelic
  - monitoring
