apiVersion: v2
name: newrelic-infrastructure
description: A Helm chart to deploy the New Relic Kubernetes monitoring solution
home: https://docs.newrelic.com/docs/kubernetes-pixie/kubernetes-integration/get-started/introduction-kubernetes-integration/
icon: https://newrelic.com/themes/custom/curio/assets/mediakit/NR_logo_Horizontal.svg
sources:
  - https://github.com/newrelic/nri-kubernetes/
  - https://github.com/newrelic/helm-charts/tree/master/charts/newrelic-infrastructure

version: 3.2.0
appVersion: 3.1.1
kubeVersion: ">=1.16.0-0"

dependencies:
  - name: common-library
    version: 0.17.2
    repository: "https://helm-charts.newrelic.com"

maintainers:
  - name: alvarocabanas
    url: https://github.com/alvarocabanas
  - name: carlossscastro
    url: https://github.com/carlossscastro
  - name: gsanchezgavier
    url: https://github.com/gsanchezgavier
  - name: kang-makes
    url: https://github.com/kang-makes
  - name: paologallinaharbur
    url: https://github.com/paologallinaharbur
  - name: roobre
    url: https://github.com/roobre

keywords:
  - infrastructure
  - newrelic
  - monitoring
