{{- if and (include "newrelic.areValuesValid" .) .Values.enableLinux }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: {{ .Release.Namespace }}
  labels: {{ include "newrelic.labels" . | indent 4 }}
  name: {{ template "newrelic.fullname" . }}-kubelet
  {{- if .Values.daemonSet.annotations }}
  annotations: {{ toYaml .Values.daemonSet.annotations | nindent 4 }}
  {{- end }}
spec:
  {{ include "newrelic.updateStrategy" . | indent 2 }}
  selector:
    matchLabels:
      app: {{ template "newrelic.name" . }}
      release: {{.Release.Name }}
  template:
    metadata:
    {{- if .Values.podAnnotations }}
      annotations:
{{ toYaml .Values.podAnnotations | indent 8}}
    {{- end }}
      labels:
        app: {{ template "newrelic.name" . }}
        release: {{.Release.Name }}
        {{- if .Values.podLabels}}
{{ toYaml .Values.podLabels | indent 8 }}
        {{- end }}
        mode: {{ template "newrelic.mode" . }}
    spec:
      serviceAccountName: {{ template "newrelic.serviceAccountName" . }}
      {{- if .Values.privileged }}
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      {{- end }}
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.image.pullSecrets | indent 8 }}
      {{- end }}
      containers:
        - name: kubelet
          image: {{ .Values.scraperImage.repository }}:{{ .Values.scraperImage.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.scraperImage.pullPolicy }}
          securityContext:
            runAsUser: {{ .Values.runAsUser }}
            runAsGroup: {{ .Values.runAsGroup }}
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
          env:
            - name: "HTTP_SERVER_PORT"
              value: {{ .Values.kubelet.httpServerPort | quote }}
            - name: "KUBELET_ENABLED"
              value: "true"
            - name: "CLUSTER_NAME"
              value: {{ include "newrelic.cluster" . }}
            - name: "NRK8S_NODE_NAME"
              valueFrom:
                fieldRef:
                  apiVersion: "v1"
                  fieldPath: "spec.nodeName"
          volumeMounts:
            - mountPath: /var/cache/nr-kubernetes
              name: tmpfs-cache
            - mountPath: /tmp
              name: tmpfs-tmp
          {{- if .Values.resources }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
          {{- end }}
        - name: agent
          image: {{ .Values.agentImage.repository }}:{{ .Values.agentImage.tag }}
          imagePullPolicy: {{ .Values.agentImage.pullPolicy }}
          securityContext:
            {{- if .Values.privileged }}
            privileged: true
            {{- else }}
            runAsUser: {{ .Values.runAsUser }}
            runAsGroup: {{ .Values.runAsGroup }}
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            {{- end }}
          ports:
            - containerPort: {{ .Values.kubelet.httpServerPort }}
          env:
            - name: "NRIA_HTTP_SERVER_PORT"
              value: {{ .Values.kubelet.httpServerPort | quote }}
            - name: NRIA_LICENSE_KEY
              valueFrom:
                secretKeyRef:
                  {{- if (include "newrelic.licenseKey" .) }}
                  name: {{ template "newrelic.fullname" . }}-config
                  key: license
                  {{- else }}
                  name: {{ include "newrelic.customSecretName" . }}
                  key: {{ include "newrelic.customSecretLicenseKey" . }}
                  {{- end }}
            {{- if .Values.eventQueueDepth }}
            - name: "NRIA_EVENT_QUEUE_DEPTH"
              value: {{ .Values.eventQueueDepth | quote }}
            {{- end }}
            {{- /* Ugly hack to check if .Values.enableProcessMetrics is defined: */}}
            {{- if ne (print .Values.enableProcessMetrics) "<nil>" }}
            - name: "NRIA_ENABLE_PROCESS_METRICS"
              value: {{ .Values.enableProcessMetrics | quote }}
            {{- end }}
            {{- if (include "newrelic.nrStaging" .) }}
            - name: "NRIA_STAGING"
              value: "true"
            {{- end }}
            {{- if .Values.useNodeNameAsDisplayName }}
            - name: "NRIA_DISPLAY_NAME"
            {{- if .Values.prefixDisplayNameWithCluster }}
              value: "{{ include "newrelic.cluster" . }}:$(NRK8S_NODE_NAME)"
            {{- else }}
              valueFrom:
                fieldRef:
                  apiVersion: "v1"
                  fieldPath: "spec.nodeName"
            {{- end }}
            {{- end }}
            {{- if .Values.customAttributes }}
            - name: "NRIA_CUSTOM_ATTRIBUTES"
              value: {{ .Values.customAttributes }}
            {{- end }}
            {{- if .Values.verboseLog }}
            - name: NRIA_VERBOSE
              value: "1"
            {{- end }}
            {{- if .Values.logFile }}
            - name: NRIA_LOG_FILE
              value: {{ .Values.logFile }}
            {{- end }}
            {{- if not .Values.privileged }}
            - name: "NRIA_OVERRIDE_HOST_ROOT"
              value: ""
            - name: "NRIA_IS_SECURE_FORWARD_ONLY"
              value: "true"
            {{- end }}
          volumeMounts:
            {{- if .Values.config }}
            - name: config
              mountPath: /etc/newrelic-infra.yml
              subPath: newrelic-infra.yml
            {{- end }}
            {{- if .Values.integrations_config }}
            - name: nri-integrations-cfg-volume
              mountPath: /etc/newrelic-infra/integrations.d/
            {{- end }}
            {{- if .Values.privileged }}
            - name: dev
              mountPath: /dev
            {{- if and (.Values.openshift.enabled) (eq .Values.openshift.version "4.x") }}
            - name: host-crio-socket
              mountPath: /var/run/crio.sock
            {{- else }}
            - name: host-docker-socket
              mountPath: /var/run/docker.sock
            {{- end }}
            - name: log
              mountPath: /var/log
            - name: host-volume
              mountPath: /host
              readOnly: true
            {{- else }}
            - mountPath: /var/db/newrelic-infra/data
              name: tmpfs-data
            - mountPath: /var/db/newrelic-infra/user_data
              name: tmpfs-user-data
            - mountPath: /tmp
              name: tmpfs-tmp
            {{- end }}
          {{- if .Values.resources }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
          {{- end }}
      volumes:
        {{- if .Values.privileged }}
        - name: dev
          hostPath:
            path: /dev
        {{- if and (.Values.openshift.enabled) (eq .Values.openshift.version "4.x") }}
        - name: host-crio-socket
          hostPath:
            path: /var/run/crio.sock
        {{- else }}
        - name: host-docker-socket
          hostPath:
            path: /var/run/docker.sock
        {{- end }}
        - name: log
          hostPath:
            path: /var/log
        - name: host-volume
          hostPath:
            path: /
        {{- else }}
        - name: tmpfs-data
          emptyDir: {}
        - name: tmpfs-user-data
          emptyDir: {}
        {{- end }}
        - name: tmpfs-tmp
          emptyDir: {}
        - name: tmpfs-cache
          emptyDir: {}
        {{- if .Values.config }}
        - name: config
          configMap:
            name: {{ template "newrelic.fullname" . }}
            items:
            - key: newrelic-infra.yml
              path: newrelic-infra.yml
        {{- end }}
        {{- if .Values.integrations_config }}
        - name: nri-integrations-cfg-volume
          configMap:
            name: {{ template "newrelic.fullname" . }}-integrations-cfg
        {{- end }}
      {{- if $.Values.priorityClassName }}
      priorityClassName: {{ $.Values.priorityClassName }}
      {{- end }}
      {{- if .Values.nodeAffinity }}
      affinity:
        nodeAffinity: {{ .Values.nodeAffinity | toYaml | nindent 10 }}
      {{- else if include "newrelic.fargate" . }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: eks.amazonaws.com/compute-type
                    operator: NotIn
                    values:
                      - fargate
      {{- end }}
      {{- if $.Values.nodeSelector }}
      nodeSelector:
{{ toYaml $.Values.nodeSelector | indent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
      {{- end }}
{{- end }}
