apiVersion: v2
version: 1.15.0-devel
description: This chart creates e2e resources for nri-kubernetes.
name: e2e-resources

dependencies:
  - name: kube-state-metrics
    version: 6.1.5
    repository: https://prometheus-community.github.io/helm-charts
  - name: common-library
    version: 1.3.3
    repository: "https://helm-charts.newrelic.com"

maintainers:
  - name: dbudziwojskiNR
    url: https://github.com/dbudziwojskiNR
  - name: tmnguyen12
    url: https://github.com/tmnguyen12
  - name: kondracek-nr
    url: https://github.com/kondracek-nr
