apiVersion: v2
version: 1.8.0-devel
description: This chart creates e2e resources for nri-kubernetes.
name: e2e-resources

dependencies:
  - name: kube-state-metrics
    version: 5.12.1
    repository: https://prometheus-community.github.io/helm-charts

maintainers:
  - name: nserrino
    url: https://github.com/nserrino
  - name: philkuz
    url: https://github.com/philkuz
  - name: htroisi
    url: https://github.com/htroisi
  - name: juanjjaramillo
    url: https://github.com/juanjjaramillo
  - name: svetlanabrennan
    url: https://github.com/svetlanabrennan
  - name: nrepai
    url: https://github.com/nrepai
  - name: csongnr
    url: https://github.com/csongnr
  - name: xqi-nr
    url: https://github.com/xqi-nr
